# This is a TOML document about the object type abbreviations.
[object_type]
b = ["bool"]
by = ["byte"]
c = ["char"]
s = ["string"]
f32 = ["float32"]
f64 = ["float64"]
i = ["int"]
i8 = ["int8"]
i16 = ["int16"]
i32 = ["int32"]
i64 = ["int64"]
u = ["uint"]
u8 = ["uint8"]
u16 = ["uint16"]
u32 = ["uint32"]
u64 = ["uint64"]
st = ["struct"]
cl = ["class"]
con = ["const"]
ch = ["chan"]
ifc = ["interface"]
m = ["map"]
func = ["function"]
arr = ["array"]
v = ["vector"]
p = ["pointer"]
j = ["json"]
q = ["queue"]
stk = ["stack"]