[a]
abbr=["abbreviation"]
abrt=["abort"]
abs=["absolute","abstract"]
acc=["account","accuracy"]
ack=["acknowledge","acknowledgement"]
act=["action","activity"]
adapt=["adapter"]
addr=["address"]
admin=["administration","administrator"]
adr=["android"]
adv=["advance"]
agg=["aggregate"]
algo=["algorithm"]
alias=["alias"]
alloc=["allocate","allocation"]
alrdy=["already"]
alrm=["alarm"]
alt=["alternate"]
amt=["amount"]
anal=["analyze","analysis"]
ans=["answer"]
annot=["annotation"]
app=["application"]
append=["append"]
arch=["architecture","archive"]
arg=["argument"]
arith=["arithmetic"]
arr=["array"]
artif=["artifact"]
asc=["ascend"]
asm=["assemble"]
asrt=["assert"]
asst=["assistant"]
assoc=["associate","association"]
async=["asynchronization","asynchronous"]
atom=["atomic"]
attach=["attach"]
attr=["attribute"]
audit=["audit"]
auth=["authenticate","authentication"]
authcode=["authentication code"]
auto=["automatic","automation"]
avail=["available","availability"]
avg=["average"]
await=["await"]
aux=["auxiliary"]
axis=["axis"]