[c]
calc=["calculate"]
char=["character"]
chg=["change"]
chk=["check"]
clr=["clear","color"]
clk=["click","clock"]
cli=["command line interface","client"]
cmd=["command"]
cmp=["compare"]
cnt=["count"]
col=["column"]
comm=["common","communication"]
cont=["content"]
conf=["config"]
conn=["connection"]
cons=["construct"]
conv=["convert"]
coord=["coordinates"]
cpl=["complete"]
cp=["copy"]
crt=["create","correct","court"]
csm=["consumer"]
csr=["cursor"]
ctrl=["control"]
ctx=["context"]
cter=["counter"]
cur=["current"]
cyl=["cylinder"]