[d]
data=["data"]
date=["date"]
datetime=["datetime"]
db=["database"]
dbg=["debug"]
dbl=["double"]
de=["decentralized"]
deco=["decode"]
decrypt=["decrypt"]
decr=["decrease","decrement"]
dedup=["deduplicate", "deduplication"]
deep=["deep"]
def=["define"]
deg=["degree"]
del=["delete"]
demo=["demo", "demonstration"]
dep=["dependency"]
deploy=["deploy", "deployment"]
depth=["depth"]
dept=["department"]
derive=["derive"]
desc=["descriptor","description","descend"]
dese=["deserialize"]
detach=["detach"]
detect=["detect", "detection"]
determine=["determine"]
dev=["device","develop"]
dex=["decentralized exchange"]
dflt=["default"]
dgst=["digest"]
dial=["dial"]
dict=["dictionary"]
diff=["different","difference"]
dig=["digit"]
dim=["dimension"]
dir=["directory", "direction"]
dis=["disable"]
disk=["disk"]
disp=["display"]
dispatch=["dispatch"]
dist=["distribution","distance"]
div=["divide"]
dlg=["dialog"]
dly=["delay"]
doc=["document", "documentation"]
domain=["domain"]
dot=["dot"]
down=["down", "download"]
download=["download"]
drag=["drag"]
draw=["draw"]
drct=["direct"]
drop=["drop"]
drv=["driver"]
ds=["dataset"]
dst=["destination"]
dto=["data transfer object", "dto"]
dump=["dump"]
dup=["duplicate", "duplication"]
dur=["duration"]
dyn=["dynamic"]
