[e]
eff=["effective"]
elec=["electric"]
exec=["execute"]
exe=["executable file"]
env=["enviroment"]
err=["error"]
ext=["extension"]
enc=["encode"]
en=["enable"]
eng=["engine"]
eq=["equal"]
eth=["ethernet"]
excep=["exception"]
expa=["expand"]
exp=["experiment"]
expi=["expiration"]
expo=["exponent","exposure"]