[m]
mag=["magnitude"]
map=["map", "mapping"]
man=["manual"]
mant=["mantissa"]
mar=["marshal"]
match=["match", "matching"]
math=["math", "mathematics"]
mat=["matrix"]
max=["maximum"]
mbox=["mailbox"]
md=["markdown"]
mdl=["model"]
meas=["measure"]
mem=["memory","member"]
meta=["metadata", "meta"]
method=["method"]
metric=["metric", "metrics"]
mft=["manufacturer"]
mgr=["manager"]
mgmt=["management"]
micro=["micro"]
mid=["middle"]
millis=["milliseconds", "millis"]
min=["minimum"]
mirror=["mirror"]
misc=["miscellaneous"]
mix=["mix", "mixing"]
mk=["make"]
mkt=["market"]
mock=["mock", "mocking"]
mnt=["mount"]
mod=["mode","module","modulus","modification"]
monitor=["monitor", "monitoring"]
month=["month"]
mouse=["mouse"]
msk=["mask"]
msg=["message"]
mul=["multiply","multiplication"]
mult=["multiple","multiplex"]
mut=["mutable", "mutate"]
mtx=["mutex"]
mv=["move"]
mux=["multiplexer"]
