[m]
mag=["magnitude"]
mbox=["mailbox"]
mk=["make"]
mgr=["manager"]
mant=["mantissa"]
man=["manual"]
mft=["manufacturer"]
md=["markdown"]
mar=["marshal"]
unmar=["unmarshal"]
msk=["mask"]
max=["maximum"]
msg=["message"]
mem=["memory"]
mid=["middle"]
min=["minimum"]
mul=["multiply","multiplex"]
mu=["mutex"]
mov=["move"]
meas=["measure"]